### PR TITLE
Sphinx provides many RST directives for logical markup.

### PR DESCRIPTION
**Pull request by ypid**
http://sphinx-doc.org/markup/inline.html

This is an example which features could be used in the DebOps project.

### CODE REVIEW

**Comment by ypid** [comment]
About the error:

```
Warning, treated as error:
/home/travis/build/debops/ansible-atd/docs/getting-started.rst:62: WARNING: u'option' reference target not
found: --tags
```

The `option` role/directive tries to reference a previously given command line help, if one is available. But as `sphinx-build` is run with `-n Run in nit-picky mode, warn about all missing references.` during testing it becomes a problem.

http://sphinx-doc.org/markup/inline.html#role-option

I disabled the `option` stuff which is preferred over disabling the `-n` option.

**Comment by ypid** [comment]
@drybjed Do you want to use these Sphinx extensions in DebOps or stick to the current way of documentation?

**Comment by drybjed** [comment]
@ypid When I looked at the rendered RTD page the commands weren't that impressive, but I suspect it's just an issue with CSS. If it can help render the docs in the future, why not? We can use them.

**Comment by ypid** [comment]
Sure, that’s what I was thinking also.

**Pull request merged**
